### ISSUE TITLE
cocoapods？

### ISSUE THREAD

**Issue by misuqian** [DJI-Mobile-SDK-Tutorials/iOS-FPVDemo#2] opened 2016-03-06 12:53 UTC
wish DJI-Mobile-SDK can add cocoapods version

**Comment by cuijiemmx** [comment] 2016-03-13 10:57
+1

**Comment by dji-dev** [comment] 2016-03-14 06:57
Hi! Thanks for your suggestions, we will consider to add cocoapods support for iOS SDK soon.

**Comment by oliverou** [comment] 2016-04-05 06:43
Hi, DJI iOS SDK 3.1.1 is now available on Cocoapods, here is the link: https://cocoapods.org/pods/DJI-SDK-iOS

**Comment by oliverou** [comment] 2016-04-28 08:00
Since the problem is fixed, I will close this issue. Thanks!

**Closed as completed by oliverou** 2016-04-28 08:00 UTC
